version = 1

test_patterns = [
  'tests/*'
]

exclude_patterns = [
  'tests/fixtures/*'
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '3.x.x'

  [analyzers.meta]
  max_line_length = 80

[[analyzers]]
name = 'test-coverage'
enabled = true
