language: python

python: 3.6

install:
  - pip install pipenv
  - pip install -e .
  - pipenv install --dev --ignore-pipfile

script:
  - pytest
  - mypy wemake_python_styleguide tests

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: sobolevn
  password: $PYPI_PASSWORD  # password is hidden
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
