# Default style file for nitpick
# and `wemake-python-styleguide` users:
# https://raw.githubusercontent.com/andreoliwa/nitpick/v0.18.0/nitpick-style.toml

[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
  "styles/flake8.toml",
  "styles/isort.toml"
]
